# Available under the EUPL-1.2, or, at your option, any later version.
# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: 2025 Universiteit Leiden <m.a.staal [at] law.leidenuniv.nl>

name: parlhist
services:
  parlhist:
    image: parlhist:latest
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    volumes:
      - parlhist-data:/data
    environment:
      PARLHIST_DJANGO_SECRET_KEY: ${PARLHIST_DJANGO_SECRET_KEY}
      PARLHIST_DEBUG: ${PARLHIST_DEBUG}
      PARLHIST_DJANGO_ALLOWED_HOSTS: ${PARLHIST_DJANGO_ALLOWED_HOSTS}
      PARLHIST_DATABASE: ${PARLHIST_DATABASE}
      PARLHIST_DJANGO_LOG_LEVEL: ${PARLHIST_DJANGO_LOG_LEVEL}
      PARLHIST_MEMOIZED_REQUESTS_PATH: "/data/memoized-requests"
      PARLHIST_ENABLE_MEMOIZATION: "True"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - parlhist-db:/var/lib/postgresql/data
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:latest
    restart: always

volumes:
  parlhist-data:
  parlhist-db:

