version: '3'
services:
  parlhist:
    image: localhost/parlhist:latest
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    volumes:
      - parlhist-data:/data
    environment:
      PARLHIST_DATABASE: "sqlite3"
      PARLHIST_MEMOIZED_REQUESTS_PATH: "/data/memoized-requests"
      PARLHIST_ENABLE_MEMOIZATION: "True"
  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #     POSTGRES_USER: ${POSTGRES_USER}

volumes:
  parlhist-data: