#!/bin/bash

./manage.py kamerstukken_crawl_year 1995
./manage.py kamerstukken_crawl_year 1996
./manage.py kamerstukken_crawl_year 1997
./manage.py kamerstukken_crawl_year 1998
./manage.py kamerstukken_crawl_year 1999
./manage.py kamerstukken_crawl_year 2000
./manage.py kamerstukken_crawl_year 2001
./manage.py kamerstukken_crawl_year 2002
./manage.py kamerstukken_crawl_year 2003
./manage.py kamerstukken_crawl_year 2004
./manage.py kamerstukken_crawl_year 2005
./manage.py kamerstukken_crawl_year 2006
./manage.py kamerstukken_crawl_year 2007
./manage.py kamerstukken_crawl_year 2008
./manage.py kamerstukken_crawl_year 2009
./manage.py kamerstukken_crawl_year 2010
./manage.py kamerstukken_crawl_year 2011
./manage.py kamerstukken_crawl_year 2012
./manage.py kamerstukken_crawl_year 2013
./manage.py kamerstukken_crawl_year 2014
./manage.py kamerstukken_crawl_year 2015
./manage.py kamerstukken_crawl_year 2016
./manage.py kamerstukken_crawl_year 2017
./manage.py kamerstukken_crawl_year 2018
./manage.py kamerstukken_crawl_year 2019
./manage.py kamerstukken_crawl_year 2020
./manage.py kamerstukken_crawl_year 2021
./manage.py kamerstukken_crawl_year 2022
./manage.py kamerstukken_crawl_year 2023
./manage.py kamerstukken_crawl_year 2024
