#!/bin/bash

./manage.py crawl_all_kamerstukken_year 1995
./manage.py crawl_all_kamerstukken_year 1996 
./manage.py crawl_all_kamerstukken_year 1997 
./manage.py crawl_all_kamerstukken_year 1998 
./manage.py crawl_all_kamerstukken_year 1999 
./manage.py crawl_all_kamerstukken_year 2000 
./manage.py crawl_all_kamerstukken_year 2001 
./manage.py crawl_all_kamerstukken_year 2002 
./manage.py crawl_all_kamerstukken_year 2003 
./manage.py crawl_all_kamerstukken_year 2004 
./manage.py crawl_all_kamerstukken_year 2005 
./manage.py crawl_all_kamerstukken_year 2006 
./manage.py crawl_all_kamerstukken_year 2007 
./manage.py crawl_all_kamerstukken_year 2008 
./manage.py crawl_all_kamerstukken_year 2009 
./manage.py crawl_all_kamerstukken_year 2010 
./manage.py crawl_all_kamerstukken_year 2011 
./manage.py crawl_all_kamerstukken_year 2012 
./manage.py crawl_all_kamerstukken_year 2013 
./manage.py crawl_all_kamerstukken_year 2014 
./manage.py crawl_all_kamerstukken_year 2015 
./manage.py crawl_all_kamerstukken_year 2016 
./manage.py crawl_all_kamerstukken_year 2017 
./manage.py crawl_all_kamerstukken_year 2018 
./manage.py crawl_all_kamerstukken_year 2019 
./manage.py crawl_all_kamerstukken_year 2020 
./manage.py crawl_all_kamerstukken_year 2021 
./manage.py crawl_all_kamerstukken_year 2022 
./manage.py crawl_all_kamerstukken_year 2023 
./manage.py crawl_all_kamerstukken_year 2024 
