# Generated by Django 5.0.1 on 2024-02-05 11:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KamerstukDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossiernummer', models.CharField(max_length=64)),
                ('dossiertitel', models.TextField()),
                ('toegevoegd_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dossiernummer'], name='parlhistnl__dossier_0d0981_idx')],
            },
        ),
        migrations.CreateModel(
            name='Kamerstuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vergaderjaar', models.CharField(max_length=8)),
                ('ondernummer', models.CharField(max_length=64)),
                ('kamer', models.CharField(choices=[('ek', 'Eerste Kamer'), ('tk', 'Tweede Kamer')], default='tk', max_length=2)),
                ('kamerstuktype', models.CharField(choices=[('Koninklijke boodschap', 'Koninklijke Boodschap'), ('Geleidende brief', 'Geleidende Brief'), ('Voorstel van wet', 'Wetsvoorstel'), ('Memorie van toelichting', 'Memorie Van Toelichting'), ('Advies Raad van State', 'Advies Rvs'), ('Voorlichting van de Afdeling advisering van de Raad van State', 'Voorlichting Rvs'), ('Verslag', 'Verslag'), ('Nota naar aanleiding van het verslag', 'Nota Na Verslag'), ('Nota van wijziging', 'Nota Van Wijziging'), ('Memorie van antwoord', 'Memorie Van Antwoord'), ('Amendement', 'Amendement'), ('Motie', 'Motie'), ('Brief', 'Brief'), ('Jaarverslag', 'Jaarverslag'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=256)),
                ('documenttitel', models.TextField()),
                ('indiener', models.TextField()),
                ('tekst', models.TextField()),
                ('raw_html', models.TextField()),
                ('raw_metadata_xml', models.TextField()),
                ('toegevoegd_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
                ('hoofddossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlhistnl.kamerstukdossier')),
            ],
        ),
        migrations.CreateModel(
            name='Vergadering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vergaderjaar', models.CharField(max_length=8)),
                ('nummer', models.IntegerField()),
                ('kamer', models.CharField(choices=[('ek', 'Eerste Kamer'), ('tk', 'Tweede Kamer')], default='tk', max_length=2)),
                ('vergaderdatum', models.DateField(default=datetime.date(1800, 1, 1))),
                ('toegevoegd_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vergaderjaar', 'nummer', 'kamer'], name='parlhistnl__vergade_33cec8_idx'), models.Index(fields=['vergaderjaar', 'nummer', 'kamer', 'vergaderdatum'], name='parlhistnl__vergade_8a114b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Handeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ondernummer', models.IntegerField()),
                ('titel', models.TextField()),
                ('handelingtype', models.CharField(max_length=1024)),
                ('tekst', models.TextField()),
                ('raw_html', models.TextField()),
                ('raw_metadata_xml', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('toegevoegd_op', models.DateTimeField(auto_now_add=True)),
                ('bijgewerkt_op', models.DateTimeField(auto_now=True)),
                ('behandelde_kamerstukken', models.ManyToManyField(to='parlhistnl.kamerstuk')),
                ('behandelde_kamerstukdossiers', models.ManyToManyField(to='parlhistnl.kamerstukdossier')),
                ('vergadering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlhistnl.vergadering')),
            ],
        ),
        migrations.AddIndex(
            model_name='kamerstuk',
            index=models.Index(fields=['vergaderjaar'], name='parlhistnl__vergade_7840d5_idx'),
        ),
        migrations.AddIndex(
            model_name='kamerstuk',
            index=models.Index(fields=['kamerstuktype'], name='parlhistnl__kamerst_86fb46_idx'),
        ),
        migrations.AddIndex(
            model_name='kamerstuk',
            index=models.Index(fields=['hoofddossier', 'ondernummer'], name='parlhistnl__hoofddo_2e5f13_idx'),
        ),
        migrations.AddIndex(
            model_name='kamerstuk',
            index=models.Index(fields=['hoofddossier', 'ondernummer', 'kamer'], name='parlhistnl__hoofddo_f6017b_idx'),
        ),
        migrations.AddIndex(
            model_name='handeling',
            index=models.Index(fields=['vergadering', 'ondernummer'], name='parlhistnl__vergade_87e50e_idx'),
        ),
    ]
