# Generated by Django 5.0.4 on 2024-06-12 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlhistnl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamerstuk',
            name='documentdatum',
            field=models.DateField(default=datetime.date(1800, 1, 1), help_text='Datum van het document volgens DCTERMS.issued'),
        ),
    ]
