# Generated by Django 5.0.6 on 2024-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0002_kamerstuk_documentdatum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staatsblad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jaargang", models.IntegerField()),
                ("nummer", models.IntegerField()),
                ("titel", models.TextField()),
                ("tekst", models.TextField()),
                ("raw_html", models.TextField()),
                ("raw_metadata_xml", models.TextField()),
                ("publicatiedatum", models.DateField()),
                ("ondertekendatum", models.DateField()),
                ("toegevoegd_op", models.DateTimeField(auto_now_add=True)),
                ("bijgewerkt_op", models.DateTimeField(auto_now=True)),
                (
                    "staatsblad_type",
                    models.CharField(
                        choices=[
                            ("Wet", "Wet"),
                            ("AMvB", "Amvb"),
                            ("Verbeterblad", "Verbeterblad"),
                            ("Onbekend", "Onbekend"),
                        ],
                        default="Onbekend",
                        max_length=256,
                    ),
                ),
                (
                    "behandelde_dossiers",
                    models.ManyToManyField(to="parlhistnl.kamerstukdossier"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["jaargang", "nummer"],
                        name="parlhistnl__jaargan_c2375a_idx",
                    )
                ],
            },
        ),
    ]
