# Generated by Django 5.0.6 on 2024-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0003_staatsblad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kamerstuk",
            name="kamerstuktype",
            field=models.CharField(
                choices=[
                    ("Koninklijke boodschap", "Koninklijke Boodschap"),
                    ("Geleidende brief", "Geleidende Brief"),
                    ("Voorstel van wet", "Wetsvoorstel"),
                    ("Memorie van toelichting", "Memorie Van Toelichting"),
                    ("Advies Raad van State", "Advies Rvs"),
                    (
                        "Voorlichting van de Afdeling advisering van de Raad van State",
                        "Voorlichting Rvs",
                    ),
                    ("Verslag", "Verslag"),
                    ("Nota naar aanleiding van het verslag", "Nota Na Verslag"),
                    ("Nota van wijziging", "Nota Van Wijziging"),
                    ("Nota van verbetering", "Nota Van Verbetering"),
                    ("Memorie van antwoord", "Memorie Van Antwoord"),
                    ("Amendement", "Amendement"),
                    ("Motie", "Motie"),
                    ("Brief", "Brief"),
                    ("Jaarverslag", "Jaarverslag"),
                    (
                        "Lijst van vragen en antwoorden",
                        "Lijst Van Vragen En Antwoorden",
                    ),
                    ("Onbekend", "Onbekend"),
                ],
                default="Onbekend",
                max_length=256,
            ),
        ),
    ]
