# Generated by Django 5.0.6 on 2024-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0004_alter_kamerstuk_kamerstuktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="staatsblad",
            name="preferred_url",
            field=models.URLField(null=True),
        ),
    ]
