# Generated by Django 5.1.5 on 2025-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0005_staatsblad_preferred_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="staatsblad",
            name="raw_xml",
            field=models.TextField(default="NO_XML_AVAILABLE"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staatsblad",
            name="staatsblad_type",
            field=models.CharField(
                choices=[
                    ("Wet", "Wet"),
                    ("AMvB", "Amvb"),
                    ("Verbeterblad", "Verbeterblad"),
                    ("Onbekend", "Onbekend"),
                    ("Klein Koninklijk Besluit", "Kkb"),
                ],
                default="Onbekend",
                max_length=256,
            ),
        ),
    ]
