# Generated by Django 5.2.1 on 2025-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0009_alter_staatsblad_staatsblad_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="staatsblad",
            name="versienummer",
            field=models.CharField(default="", max_length=16),
        ),
    ]
