# Generated by Django 5.2.2 on 2025-06-10 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parlhistnl", "0010_staatsblad_versienummer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handeling",
            name="vergadering",
        ),
        migrations.RemoveIndex(
            model_name="handeling",
            name="parlhistnl__vergade_87e50e_idx",
        ),
        migrations.AddField(
            model_name="handeling",
            name="identifier",
            field=models.CharField(default=None, max_length=48, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="handeling",
            name="kamer",
            field=models.CharField(
                choices=[("ek", "Eerste Kamer"), ("tk", "Tweede Kamer")],
                default="tk",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="handeling",
            name="vergaderdag",
            field=models.DateField(default=datetime.date(1800, 1, 1)),
        ),
        migrations.DeleteModel(
            name="Vergadering",
        ),
    ]
